### ISSUE TITLE
Implement embedding face-ar/vto mode

### ISSUE THREAD

**Issue by DavidArayan** [Plattar/plattar-ar-adapter#18]
**About**

This functionality allows embedding Desktop VTO (Virtual Try On)/Face AR mode into existing websites. Since the Plattar VTO Renderer is a direct extension of the Plattar Configurator, the interface is a direct extension of the implementation as seen in [Issue #12](https://github.com/Plattar/plattar-ar-adapter/issues/12).

This functionality is reliant on the AR Implementation as defined in [Issue #7](https://github.com/Plattar/plattar-ar-adapter/issues/7).

**Proposal & Interface Example**

Add an additional enumerator type to `plattar-embed` attribute named `vto`. This would allow the node to initialise the face-ar/vto renderer. This node also allows launching a VTO AR Experience for supported IOS Devices.

- Example of a standard viewer embed

```html
<!-- embed-type attribute is optional and defaults to "viewer" type -->
<plattar-embed scene-id="SCENE_ID" embed-type="viewer" />
<!-- OR -->
<plattar-embed scene-id="SCENE_ID" />
```

- Example of a Desktop VTO/Face AR embed

```html
<plattar-embed scene-id="SCENE_ID" embed-type="vto" />
```

- Final Example of a Desktop VTO/Face AR embed with all attributes

```html
<!-- Loads a face ar with provided scene and provided state whilst showing an AR Button -->
<plattar-embed scene-id="SCENE_ID" embed-type="vto" config-state="CONFIG_STATE" show-ar="true" />
```

**Problems, Issues & Limitations**

1. Desktop VTO only functions for desktop/non-mobile devices. If the node is initialised on mobile devices, the standard Plattar Viewer will be rendered instead.
2. `show-ar` will only display an AR button for IOS Devices. This is because there is no current support for Android devices for launching a VTO Experience.
3. Launching AR Mode only works for IOS Devices. Same limitation as point 2.

**Comment by calrk** [comment]
I think `embed-type` should be one of `viewer` or `vto` as desktop VTO is used for both desktop and android. if android comes up with its own VTO in future, then we can change it to use that.

The viewer should not be shown in place of the VTO.

If `embed-type` is blank, then it should get the anchor from the scene object and choose viewer or vto from that.

I dont understand show-ar property, cause this will be initiated by code like 
```
ar.launch().then(() => {
    console.log("success");
}).catch((err) => {
    console.log(err);
});
```

Also why is this using html node instead of the SceneAR() functionality?

**Comment by DavidArayan** [comment]
@calrk 

`embed-type="viewer"` is already taken and is used to initialise the internal `<plattar-viewer />` node. I agree with changing `desktop-vto` to `vto`. Initially I didn't think the VTO would be used for Android aswell (i'll update the docs).

`embed-type` being blank is also the default functionality which is used to initialise the `<plattar-viewer />` node aswell. To get the anchor, a GET request needs to be done against the Scene which is something i'd like to avoid when initialising the node (saves API bandwidth).

SceneAR is used internally as part of the `<plattar-embed />` node. Just to clarify, this is how it would work which is consistent with all other integrations running on the new Renderer.

`show-ar` is a Plattar Renderer flag that shows the default AR button in the Plattar Viewer.

```html
<body>
    <plattar-embed id="embed" scene-id="SCENE_ID" width="512px" height="512px"
        embed-type="vto" />

    <script>
        const embed = document.getElementById("embed");

        // We support Reality Viewer and can launch a Reality VTO
        if (PlattarARAdapter.Util.canRealityViewer()) {
            // This will launch a Reality VTO for provided scene-id
            // can always create a HTML button and listen for user
            // click before calling this function (up to implementation)
            embed.startAR().then(() => {
                // AR launched successfully - this uses SceneAR internally
            }).catch((err) => {
                // AR failed to launch
            });
        }
        else {
            // looks like we are either in desktop or android
            // simply launch the face-ar desktop/android VTO
            embed.startViewer().then(() => {
                // Viewer launched successfully
                // This uses <plattar-facear /> internally
            }).catch((err) => {
                // Viewer failed to launch
            });
        }
    </script>
</body>
```
