### ISSUE TITLE
VR not opening

### ISSUE THREAD

**Issue by LucasVilela** [Plattar/plattar-ar-adapter#2]
I'm having a problem with this implementation, The AR is not opening. I'm testing on iPhone 13 and the models are from Bailey Nelson glasses

Here is the sandbox:
https://codesandbox.io/s/goofy-sound-k67cx?file=/src/App.tsx

Is there anything that I'm doing wrong?

**Comment by DavidArayan** [comment]
Hello @LucasVilela,

Looking at the code you've posted on Line 24 in the `runProductAR()` function

```javascript
const webAR: ProductAR = new ProductAR(plattarVariationId);
```

should instead be

```javascript
const plattarProductId = "278ca070-d2ff-11ea-88d8-e38d12dd03b6";
const webAR: ProductAR = new ProductAR(plattarProductId, plattarVariationId);
```

The ProductAR node requires both a Product and a Variation.
