### ISSUE TITLE
Making variation selection easier to use and more general across the embed methods.

### ISSUE THREAD

**Issue by calrk** [Plattar/plattar-ar-adapter#59]
1) Swapping variation-id without scene-product-id or product-id.
Since we can iterate through the products and their variations, we don't need to store the main product-ids
<plattar-embed id="embed_viewer" scene-id="143d6c50-48fb-11ed-a0d1-33f25dd99e4e" embed-type="viewer" `variation-id='<variation-id>'`>

2) Using variation-sku as an attributes
if variation-id and variation-sku clash, then take the newest (and console log clash error)
<plattar-embed id="embed_viewer" scene-id="143d6c50-48fb-11ed-a0d1-33f25dd99e4e" embed-type="viewer" `variation-sku='<variation-sku>'`>

3) Swapping embed-type from viewer to facear updates in real time

4) Having any variation changes propagate upwards into the tag's config-state

**Comment by DavidArayan** [comment]
@calrk feedback appreciated on my thoughts below

## Swapping variation-id without scene-product-id or product-id

This is doable as a search feature internally in the renderer, however it does slightly complicate the implementation for launching AR without the renderer but its still doable.

Currently the following messenger interfaces are available. I also suggest streamlining and making all these interfaces available for all renderer nodes.

1. `selectProductVariation(productID:string, variationID:string): Promise<void>;`
2. `sceneSceneProductVariation(sceneProductID:string, variationID:string): Promise<void>;`

**Solution**

I recommend adding the following messenger functionalities (alongside the old ones). This ensures backwards compatibility.

1. `selectVariation(variationID:string|Array<string>): Promise<void>;` - Enables a single Variation using a Variation ID or Enables all Variations provided a list of Variation ID's
2. `selectVariationSKU(variationSKU:string|Array<string>): Promise<void>;` - Enables a single Variation using a Variation SKU or Enabled all Variations provided a list of Variation SKU's

The new functions should map into new attributes available for `<plattar-embed />` node

1. `<plattar-embed variation-id="" />` - Calls `selectVariation(string)` or `selectVariation(array)`, Comma separated list of ID's
2. `<plattar-embed variation-sku="" />` - Calls `selectVariationSKU(string)` or `selectVariationSKU(array)`, Comma separated list of ID's

**Examples**

1. `<plattar-embed variation-id="123" />` or `<plattar-embed variation-id="123,456" />`
2. `<plattar-embed variation-sku="123" />` or `<plattar-embed variation-sku="123,456" />`

**Concerns**

1. The SKU's are not systematically unique and can be duplicates. This places the burden on content-creation or content-curators to ensure the SKU's they enter into the CMS is all unique. 
2. The SKU's cannot have commas as its used for as separator element (please check if this is OK)
3. In cases where SKU's are duplicated (aka, two separate products with variations having same SKU) how should the system handle this? swap the variation on both?

## Using variation-sku as an attributes

See above proposal

## Swapping embed-type from viewer to facear updates in real time

This is possible by internally swapping out the controller and re-initialising the renderer, however should this maintain state changes done via messenger interface?

## Having any variation changes propagate upwards into the tag's config-state

We can achieve this by having messenger callbacks (aka, calling messenger functions on the parent page called by renderer when interfaces are used)

**Comment by calrk** [comment]
Looks good, would like to see the performance impact of swapping from viewer to facear
